# Generated by Django 3.1.4 on 2021-01-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.AddField(
            model_name='transaction',
            name='frm',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='recieved', to='ctapp.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='ctapp.client'),
            preserve_default=False,
        ),
    ]
